JOB_PRODUCT=
JOB_MVN_OPTS=-Xmx512M 
JOB_INTEGRATION_SITE=false
JOB_DOCKER_LABELS=jenkins-slave-jdk11-maven
JOB_JDK=JDK21
JOB_MAVEN=Maven 3.9
JOB_REPORTERS=['junit']
JOB_FORKED_PROJECT=true
JOB_NON_SEMANTIC_VERSIONING=true
